### ISSUE TITLE
bedToMatrix.py does not work as it is desgined

### ISSUE THREAD

**Issue by yezhengSTAT** [kcakdemir/HiCPlotter#23]
Hello,
If I understand correctly, bedToMatrix.py should transform contact list into contact matrix. By saying contact matrix, it should be a symmetric matrix, isn't it? However, bedToMatrix.py will only save contact count to the row of the bin with smaller coordinates. For example:
chr1 2000_4000 16000_18000 5
contact count 5 will only be saved at row 2 column 9, instead of both row 2 column 9 and row 9 column2. Is it something that is specifically designed for HiCPlotter?

Thanks,
Ye

**Comment by kcakdemir** [comment]
Hi Ye,

I havent tested this script on a while which contains intrechromosomal interactions. I generated files from GSM1081526_TEV_r1_cis file and they are symmetric so it should output [2][9]=[9][2]. 
The script might require some editing if the input file is a bit different. Best - kadir

**Comment by yezhengSTAT** [comment]
Hi Kadir,
Sorry if I misread the following codes, however, it seems that in the example of 
chr1 2000_4000 16000_18000 5
only row 2 will be save in chromosome.keys() by ```chromosome[start][interact]=freq```. Therefore, when ```i``` equals 9, ```if i in chromosome.keys()``` will fail, hence either output max_freq at the 9th diagonal element or output 0 at all other cells in the 9th row.
```{python}
for i in range(0,last_region):
		if i in chromosome.keys():
			for x in range(0,last_region):
				if x == i:
					if x not in chromosome[i].keys():
						writer.write(str(max_freq)+'\t')
					elif x in chromosome.keys() and i in chromosome[x].keys():
						writer.write(str(chromosome[x][i])+'\t')
					elif x in chromosome[i].keys():
						writer.write(str(chromosome[i][x])+'\t')
				else:
					if x in chromosome[i].keys():
						writer.write(str(chromosome[i][x])+'\t')
					elif x in chromosome.keys() and i in chromosome[x].keys():
						writer.write(str(chromosome[x][i])+'\t')
					else:
						writer.write('0\t')
		else:
			for x in range(0,last_region):
				if x == i:
					writer.write(str(max_freq)+'\t')
				else:
					writer.write('0\t')
		writer.write('\n')
```
Best,
Ye

**Comment by kcakdemir** [comment]
Hi Ye,

I think the intention was to save memory, as you don’t have to save the values symmetrically.
When it writes the file, below lines should take care of that part.

`if x in chromosome[i].keys():
  writer.write(str(chromosome[i][x])+'\t')
elif x in chromosome.keys() and i in chromosome[x].keys():
	writer.write(str(chromosome[x][i])+'\t')`

It’s been a while since I have tested the code, so let me know if you notice any problems.

**Comment by yezhengSTAT** [comment]
Hi Kadir,
In order to get to the ```elif x in chromosome.keys() and i in chromosome[x].keys(): writer.write(str(chromosome[x][i])+'\t')```, it requires both i in chromosome.keys() and x in chromosome.keys(), namely "2" and "9" being saved in the chromosome.keys(). However in the example of 
chr1 2000_4000 16000_18000 5
only 2 is saved in the chromosome.keys().

I noticed this problem as I am running bedToMatrix.py to transform contact list of IMR90 to contact matrix. Both R function isSymmetric() and the insulation score calculation software: https://github.com/dekkerlab/crane-nature-2015 tells me the input matrix is not symmetric. I ran a shorter contact list and found the contacts are only output into corresponding rows but not columns. I think I have found the way out by modifying your script a little bit. ;)

Thanks,
Ye

**Comment by kcakdemir** [comment]
Hi Ye,

I got what you were referring to now! I assumed "9" would occur in the file so it wont store [9][2] but since 9 is in the keys, it would go to [2][9] for writing. I need to change the code or if you have something working and like to share, please send a pull request.
I wasnt sure whether those util scripts were useful to the folks, so havent updated for a while.

Thanks for pointing to the problem! I am closing this issue but please feel free to open, if need be. Kadir
