### ISSUE TITLE
HiC-Pro multiple plots

### ISSUE THREAD

**Issue by lucaspatel** [kcakdemir/HiCPlotter#24]
Hello,

I'm trying to use HiCPlotter to plot two HiC-Pro output matrices but I am having trouble. I tried something like this, ignoring extraneous flags:

`python HiCPlotter.py -f matrix1 matrix2 -tri 1 -bed bed1 bed2`

The output says it doesn't recognize the bed2 file. Then if I try just using bed1 without bed2, since really in my case both are the same, the output says "upps!! please provide equal number of hic matrix and bedgraphs."

Everything works flawlessly when plotted individually, but I really like the joint side by side visualization and would love if I could get that working.

Thank you.

**Comment by nservant** [comment]
Hi,
Did you try with only one BED file ? As I guess it is the same for both matrices ?
Best

**Comment by lucaspatel** [comment]
Yes, then the output says "upps!! please provide equal number of hic matrix and bedgraphs” since I’m providing two .matrix files but only one .bed.

**Comment by nservant** [comment]
humm ... Let see if Kadir has an idea. On my side, I'm using a quite old version but it works with only one value in the -bed field.

**Comment by kcakdemir** [comment]
Hi folks,

Nicholas is right, there should be only one bed file for multiple matrices and it should work fine.
Lucas, do you mind sharing the whole command? I think there is another issue here.

**Comment by lucaspatel** [comment]
Hello,

Nicolas was right. I typed out my command by hand again and it worked perfectly. I was actually missing one of two .bedGraph files, unrelated to HiC-Pro; these commands can get so long! Thanks for the help.

Another thing I noticed, and this perhaps is intended, is that when processing a gene file in a plot where the start to end locations do not contain any of the genes in the gene file, HiCPlotter reports an error saying "Gene File (chr1_genes.bed) has some missing values." I dug around a bit and it looks like this happens because `len(genes.keys()) ==0` which is true if no genes fall within the range, but because of the smaller range of my plots this implementation ends up killing a lot of my jobs. I've commented out the `raise SystemExit` line for now and that seems to work fine for what I want, albeit no genes are plotted on some of my ranges as expected.

Finally, I would like to highlight two different .bed file regions on my plots. Plotting one region works flawlessly, but I'd like to plot another in tandem with a different color other than green. Is this currently possible? I don't see it anywhere in the manual. Just thought I'd ask before I go and try and implement it myself.

Thanks again, HiCPlotter is a phenomenal tool.

**Comment by kcakdemir** [comment]
Hi Lucas,

Thanks for the kind words! 
I know the commands can get messy easily, unfortunately dont have a good solution for that :).
Missing value error is intentional so that user would know there is something missing. You figured where to target already.

For the highlight colors: it's a good idea and I will include it in next update. 
Meanwhile you can change 
h_start,h_end,_,_,_ = read_bedGraph(highFile,resolution,chromosome) 
to 
h_start,h_end,_,h_colors,_ = read_bedGraph(highFile,resolution,chromosome)

and replace all 
h_start[item], h_end[item], facecolor='g'
to
h_start[item], h_end[item], facecolor='#'+h_color[item]

In the highlights bed file, you should add a number in 4th column (wont be used) and 5th column should be hexadecimal numbers for each location's color.
Let me know if you encounter any problems.

**Comment by kcakdemir** [comment]
Hi guys, Im closing this issue at the moment but feel free to reopen it in case you like to discuss more...
