### ISSUE TITLE
error of plot log2 matrix with peaks

### ISSUE THREAD

**Issue by skytguuu** [kcakdemir/HiCPlotter#26]
Hi,
Recently, I tried to use HiCPlotter to plot the log2 matrix with loading peaks file, command is as followed:
####
python HiCPlotter.py -f g1_iced.matrix g2_iced.matrix -n g1 g2 -r 20000 -o compare -chr chr17 -c 1 -peaks loops.bed -ptr 0 -tri 1 -bed ref_20kb.bed
####
It reports that : Upps!! Please provide equal number of HiC matrix and peak files.

Then, I tried: "-peaks loops.bed loops.bed", but it made an error that: line2123, line 710 and line 245. 
hex ='#%02x%02x%02x' %(int(tags[6].split(',)[0]), int(tags[6].split('.')[1]),int(tags[6].split(',')[2]))
ValueError: invalid literal for int() with base 10: '"0' 

Could you give me some help?
Thank you!
Best,
Garen

**Comment by kcakdemir** [comment]
Hi Garen,

I think the issue is the columns of your peak file. You should use "-peak" (instead of "-peaks") and the columns of your peak file should be as below:

chromA	chromStartA  chromEndA	chromB	chromStartB chromEndB	color (optional)
chr10	100180000	100190000	chr10	100410000	100420000	0,255,255
chr10	101600000	101610000	chr10	101800000	101810000	0,255,255 

You can check the example on the main page under Annotating the interaction matrix. Let me know if you experience issues.

Best - Kadir

**Comment by kcakdemir** [comment]
Hi again Garen,

You can save the matrix with np.savetxt function. If you add the below line at Line 692, it should save the matrix to a text file. 
np.savetxt('matrix.txt', matrix, delimiter=',')

**Comment by skytguuu** [comment]
Dear Kadir,

It works well now. 
Thank you!

Best,
Garen
