### ISSUE TITLE
Plotting to PDF/SVG

### ISSUE THREAD

**Issue by FedericoComoglio** [kcakdemir/HiCPlotter#5]
Hi,

thanks a lot for developing HICPlotter. I was wondering if it is possible to write output files directly to a pdf/svg device. From the code

`        if 'JPEG' in plt.gcf().canvas.get_supported_filetypes_grouped().keys() or 'Joint Photographic Experts Group' in plt.gcf().canvas.get_supported_filetypes_grouped().keys(): extension='.jpeg'
        else : extension = '.png'`

it seems that only jpeg and png are supported. How could I go about generating a vectorized image?
Thank you in advance.

Best wishes,
FC

**Comment by kcakdemir** [comment]
Hi,

Thanks for using HiCPlotter! 
I initially abstained from pdf as the main extension because it was giving errors for different operating systems. But you can just add the following line after the else statement and is should work fine

if 'JPEG' in plt.gcf().canvas.get_supported_filetypes_grouped().keys() or 'Joint Photographic Experts Group' in plt.gcf().canvas.get_supported_filetypes_grouped().keys(): extension='.jpeg' 
else : extension = '.png'
**extension='.pdf'**

I will implement it in a better way in upcoming update. Please let me know if it doesnt work for you... K

**Comment by kcakdemir** [comment]
I added a new parameter: -ext. So you can run HiCPlotter with the addition of "**-ext pdf**" or several other file formats such as svg,tiff,gif etc.

**Comment by FedericoComoglio** [comment]
Thank you so much.
